In [1]:
from numpy import *

In [2]:
random.rand(4,4)

array([[0.60330561, 0.54885802, 0.20765129, 0.26923965],
       [0.1687935 , 0.56611231, 0.62088844, 0.10790535],
       [0.30927395, 0.03177413, 0.11805469, 0.77083635],
       [0.35592891, 0.8939455 , 0.87872893, 0.93493945]])

In [3]:
randMat=mat(random.rand(4,4))

In [4]:
randMat


matrix([[0.82968125, 0.06226326, 0.40433692, 0.6196608 ],
        [0.71654729, 0.53430469, 0.06337785, 0.22492381],
        [0.67207205, 0.80338005, 0.45934732, 0.93435721],
        [0.27203005, 0.42448829, 0.09410072, 0.23606592]])

In [5]:
randMat.I

matrix([[  0.46006581,   1.8203104 ,  -0.2824228 ,  -1.82420283],
        [  1.1387792 ,  -2.8836715 ,  -2.93403366,  11.37133658],
        [ 13.63271977, -20.61986585, -19.41136837,  60.69232121],
        [ -8.01216399,  11.30722219,  13.3391304 , -38.30265781]])

In [6]:
invRandMat=randMat.I

In [7]:
invRandMat*invRandMat


matrix([[   13.05021356,   -19.2148612 ,   -24.32185156,    72.59103065],
        [ -133.86782382,   199.46610265,   216.77652158,  -648.49429032],
        [ -768.11610173,  1170.79807406,  1243.03319826, -3762.14249553],
        [  497.92610902,  -755.33868166,  -800.76787377,  2419.8704236 ]])

In [8]:
randMat*invRandMat


matrix([[ 1.00000000e+00,  8.88178420e-16,  0.00000000e+00,
          0.00000000e+00],
        [-2.22044605e-16,  1.00000000e+00,  1.11022302e-15,
         -1.77635684e-15],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  6.66133815e-16,  4.44089210e-16,
          1.00000000e+00]])

In [9]:
randMat*invRandMat-eye(4)

matrix([[ 0.00000000e+00,  8.88178420e-16,  0.00000000e+00,
          0.00000000e+00],
        [-2.22044605e-16,  1.99840144e-15,  1.11022302e-15,
         -1.77635684e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  6.66133815e-16,  4.44089210e-16,
          0.00000000e+00]])